### ISSUE TITLE
Error running 2nd instance

### ISSUE THREAD

**Issue by kevinkk525** [anclrii/Storj-Exporter#1]
I tried to run a 2nd instance linked to the container "storagenode2" which runs the api on a different port externally but internally still 14002. As I understand it, the exporter docker instance links to the storagnode instance so it connects to the internal port?

```
Traceback (most recent call last):


  File "./storj-exporter.py", line 65, in <module>


    REGISTRY.register(StorjCollector())


  File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 24, in register


    names = self._get_names(collector)


  File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 64, in _get_names


    for metric in desc_func():


  File "./storj-exporter.py", line 33, in collect


    self.data = self.get_data()


  File "./storj-exporter.py", line 17, in get_data


    return self.call_api("dashboard")['data']


  File "./storj-exporter.py", line 13, in call_api


    response=requests.get(url = "http://" + self.storj_host_address + ":" + self.storj_api_port + "/api/" + path)


  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get


    return request('get', url, params=params, **kwargs)


  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request


    return session.request(method=method, url=url, **kwargs)


  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request


    resp = self.send(prep, **send_kwargs)


  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send


    r = adapter.send(request, **kwargs)


  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send


    raise ConnectionError(e, request=request)


requests.exceptions.ConnectionError: HTTPConnectionPool(host='storagenode', port=14002): Max retries exceeded with url: /api/dashboard (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55d9945a50>: Failed to establish a new connection: [Errno -2] Name does not resolve'))


Traceback (most recent call last):


  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn


    (self._dns_host, self.port), self.timeout, **extra_kw


  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection


    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):


  File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo


    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):


socket.gaierror: [Errno -2] Name does not resolve



During handling of the above exception, another exception occurred:



Traceback (most recent call last):


  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen


    chunked=chunked,


  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request


    conn.request(method, url, **httplib_request_kw)


  File "/usr/local/lib/python3.7/http/client.py", line 1244, in request


    self._send_request(method, url, body, headers, encode_chunked)


  File "/usr/local/lib/python3.7/http/client.py", line 1290, in _send_request


    self.endheaders(body, encode_chunked=encode_chunked)


  File "/usr/local/lib/python3.7/http/client.py", line 1239, in endheaders


    self._send_output(message_body, encode_chunked=encode_chunked)


  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output


    self.send(msg)


  File "/usr/local/lib/python3.7/http/client.py", line 966, in send


    self.connect()


  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 184, in connect


    conn = self._new_conn()


  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn


    self, "Failed to establish a new connection: %s" % e


urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7faf33b43990>: Failed to establish a new connection: [Errno -2] Name does not resolve



During handling of the above exception, another exception occurred:



Traceback (most recent call last):


  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send


    timeout=timeout


  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen


    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]


  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment


    raise MaxRetryError(_pool, url, error or ResponseError(cause))


urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='storagenode', port=14002): Max retries exceeded with url: /api/dashboard (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf33b43990>: Failed to establish a new connection: [Errno -2] Name does not resolve'))



During handling of the above exception, another exception occurred:



Traceback (most recent call last):


  File "./storj-exporter.py", line 65, in <module>


    REGISTRY.register(StorjCollector())


  File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 24, in register


    names = self._get_names(collector)


  File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 64, in _get_names


    for metric in desc_func():


  File "./storj-exporter.py", line 33, in collect


    self.data = self.get_data()


  File "./storj-exporter.py", line 17, in get_data


    return self.call_api("dashboard")['data']


  File "./storj-exporter.py", line 13, in call_api


    response=requests.get(url = "http://" + self.storj_host_address + ":" + self.storj_api_port + "/api/" + path)


  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get


    return request('get', url, params=params, **kwargs)


  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request


    return session.request(method=method, url=url, **kwargs)


  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request


    resp = self.send(prep, **send_kwargs)


  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send


    r = adapter.send(request, **kwargs)


  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send


    raise ConnectionError(e, request=request)


requests.exceptions.ConnectionError: HTTPConnectionPool(host='storagenode', port=14002): Max retries exceeded with url: /api/dashboard (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf33b43990>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
```

**Comment by kevinkk525** [comment]
I did run it as: docker run -d --link=storagenode2 --name=storj-exporter2 -p 9652:9651 anclrii/storj-exporter:latest
for the 2nd instance.

**Comment by anclrii** [comment]
I never tested with 2 storagenode containers, but I guess that's expected and can be resolved. 

Your error is `Failed to establish a new connection: [Errno -2] Name does not resolve')` .
It's trying to resolve `storagenode` hostname as set in `STORJ_HOST_ADDRESS` env variable but you added host `storagenode2` in your --link arg so it can not find storagenode.

Try adding `-e STORJ_HOST_ADDRESS=storagenode2` in your docker run to override the default. That should do it. 

Please report back if it worked so I can update the readme. Thanks.

**Comment by anclrii** [comment]
You may also need to override `STORJ_API_PORT` and especially `STORJ_EXPORTER_PORT`  env var when running more than one instance. Check the readme.

**Comment by kevinkk525** [comment]
ah you are right, it works now with -e STORJ_HOST_ADDRESS=storagenode2
I just assumed it would automatically use the correct host adress according to the --link arg.
