### ISSUE TITLE
storagenode 1.5.2 error

### ISSUE THREAD

**Issue by kevinkk525** [anclrii/Storj-Exporter#28]
Since the update the exporter doesn't work correctly anymore:

```
Traceback (most recent call last):
  File "./storj-exporter.py", line 128, in <module>
    REGISTRY.register(StorjCollector())
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 24, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 64, in _get_names
    for metric in desc_func():
  File "./storj-exporter.py", line 62, in collect
    value = str(self.data[key])
yError: 'lastPingFromID'
```

**Comment by phpbg** [comment]
version is *1.5.2*, not *0.5.2* (last storagenode update)

**Comment by kevinkk525** [comment]
Fixed in latest release. Thanks, you are really quick.
